# ── Input (override personal) ─────────────────────────────────
# Este archivo se carga AL FINAL del hyprland.conf, por lo que
# sus valores sobrescriben cualquier bloque input{} anterior.
input {
    kb_layout = latam
    kb_options =
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35
    sensitivity = 0
    accel_profile = flat
    follow_mouse = 1
    mouse_refocus = true

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        clickfinger_behavior = true
        scroll_factor = 0.5
        tap-to-click = true
    }
    special_fallthrough = true
}
