# ═══════════════════════════════════════════════════════════════
#  HYPRLAND.CONF — Punto de entrada principal
#  Arch Linux | GPU: Intel iGPU (render) + NVIDIA dGPU
#  Tema: Catppuccin Frappé
# ═══════════════════════════════════════════════════════════════

# 1. Tema de colores (PRIMERO: las variables deben estar disponibles para el resto)
source = ~/.config/hypr/frappe.conf

# 2. Hardware
source = ~/.config/hypr/conf/custom/monitor.conf
source = ~/.config/hypr/conf/environment.conf

# 3. Autostart
source = ~/.config/hypr/conf/autostart.conf

# 4. Visual
source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/animation.conf

# 5. Comportamiento
source = ~/.config/hypr/conf/layout.conf
source = ~/.config/hypr/conf/misc.conf
source = ~/.config/hypr/conf/windowrule.conf

# 6. Atajos y aplicaciones
source = ~/.config/hypr/conf/keybinding.conf
source = ~/.config/hypr/conf/apps.conf

# 7. Overrides personales (siempre al final — sobrescriben todo lo anterior)
source = ~/.config/hypr/conf/custom/general.conf
