general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

animations {
    enabled = true
    bezier = crazyshot, 0.1, 1.5, 0.76, 0.92
    animation = fadeIn, 1, 7, crazyshot
    animation = fadeOut, 1, 7, crazyshot
}

background {
    monitor =
    path = $HOME/.config/hypr/flow.jpg
    blur_passes = 2
    contrast = 1
    brightness = 0.9
    vibrancy = 1
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = $act_border
    inner_color = $act_border
    font_color = $inact_border
    fade_on_empty = false
    fade_timeout = 2000
    placeholder_text = <i> <span foreground="##000000"> Enter Password...</span> </i>
    hide_input = false
    rounding = -1
    check_color = $mauve
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = $yellow
    numlock_color = $yellow
    bothlock_color = $yellow
    invert_numlock = false
    swap_font_color = $act_border
    position = 0, 100
    halign = center
    valign = bottom
}

# time (hour)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%I')"
    color = $act_border
    font_size = 165
    font_family = Montserrat Italic Bold
    position = -50, 200
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}

# time (minute)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%M')"
    color = $act_border
    font_size = 165
    font_family = Montserrat Italic Bold
    position = 50, -10
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}

# date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%d %B, %Y')"
    color = $act_border
    font_size = 25
    font_family = Pacifico Regular
    position = 0, -150
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}

# Battery (Feature 4)
label {
    monitor =
    text = cmd[update:1000] echo "$(cat /sys/class/power_supply/BAT1/capacity)% $([ $(cat /sys/class/power_supply/BAT1/capacity) -le 20 ] && echo '󰂃' || echo '󰁹')"
    color = $act_border
    font_size = 14
    font_family = Montserrat
    position = -30, -30
    halign = right
    valign = top
}
