# Setup XDG
exec-once = hyprpanel

# Using hypridle to start hyprlock
exec-once = hypridle

exec-once = hyprsunset

exec-once = hyprctl setcursor Bibata-Modern-Ice 24

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
