# ── XDG ──────────────────────────────────────
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# ── Qt ───────────────────────────────────────
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORMTHEME,qt5ct

# ── GDK / GTK ────────────────────────────────
env = GDK_SCALE,1
env = GTK_THEME,Colloid-Dark-Catppuccin

# ── Mozilla / Electron ───────────────────────
env = MOZ_ENABLE_WAYLAND,1
env = SDL_VIDEODRIVER,wayland
env = ELECTRON_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

# ── VRR / Sync ───────────────────────────────
env = __GL_GSYNC_ALLOWED,1
env = __GL_VRR_ALLOWED,1

# ── NVIDIA (activo si se usa dGPU; actualmente iGPU Intel via AQ_DRM_DEVICES) ──
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = NVD_BACKEND,direct

# ── Renderer principal: iGPU Intel ───────────
env = AQ_DRM_DEVICES,/dev/dri/intel-igpu

# ── Cursores (Consistencia en XWayland) ──
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Ice
