general {
    gaps_in = 5
    gaps_out = 14
    border_size = 6
    # Gradiente en 45deg para evitar que los bordes verticales se queden en un solo color
    col.active_border = $mauve $red $yellow $green $sapphire $mauve 45deg
    col.inactive_border = $surface0
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}
