dwindle {
    pseudotile = true
    preserve_split = true
    force_split = 2        # 0=sigue al mouse, 1=split izquierda, 2=split derecha
    smart_resizing = true
}

master {
    new_status = master    # Nuevo: "master", "slave", "inherit"
    new_on_top = true
    mfact = 0.55           # Proporción del área master (0.0-1.0)
    drop_at_cursor = true
}

cursor {
    no_hardware_cursors = true # Reemplaza WLR_NO_HARDWARE_CURSORS
}
