dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    smart_resizing = true
    new_on_active = true
    drop_at_cursor = true
}

cursor {
    # Fixes nvidia issues
    no_hardware_cursors = true
}

