misc {
    vfr = false    # Desactivado para que el borderangle no se congele cuando hay inactividad en pantalla
    vrr = 1
    animate_manual_resizes = false
    animate_mouse_windowdragging = false
    enable_swallow = true
    swallow_regex = ^(alacritty|Alacritty|kitty|foot)$
    disable_splash_rendering = true
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    allow_session_lock_restore = true
    initial_workspace_tracking = 0   # 0=off, 1=por clase, 2=por instancia
}
