general {
    gaps_in = 5
    gaps_out = 14
    border_size = 4
    col.active_border = rgba(C386F1ff) rgba(A6E3A1ff) rgba(89b4faff) 10deg
    col.inactive_border = 0xff313244
    layout = dwindle
}


