-- This file is automatically generated by Matugen.
-- Do not edit manually.
return {
  primary = "#4facfe",
  on_primary = "#000000",
  surface = "#0f172a",
  on_surface = "#f8fafc",
  secondary = "#38bdf8",
  on_secondary = "#000000",
  tertiary = "#818cf8",
  error = "#ef4444",
  outline = "#475569",
}
