local M = {}

-- Path to the colors file generated by Matugen
-- Using standard Lua require for the bridge
function M.get_palette()
  local ok, colors = pcall(require, "util.noctalia_colors")
  if not ok then
    -- Fallback colors (Catppuccin Mocha-like or generic Material)
    return {
      primary = "#89b4fa",
      on_primary = "#11111b",
      surface = "#1e1e2e",
      on_surface = "#cdd6f4",
      secondary = "#f5c2e7",
      error = "#f38ba8",
      outline = "#585b70",
    }
  end
  return colors
end

-- Watch for changes in the colors file and reload catppuccin
function M.setup_watcher()
  local uv = vim.uv or vim.loop
  local handle = uv.new_fs_event()
  local colors_path = vim.fn.stdpath("config") .. "/lua/util/noctalia_colors.lua"

  handle:start(colors_path, {}, function(err, filename, events)
    if err then
      return
    end
    vim.schedule(function()
      -- Clear cache and reload
      package.loaded["util.noctalia_colors"] = nil
      vim.cmd("colorscheme catppuccin")
      -- Notify about the reload
      vim.notify("Noctalia colors updated!", vim.log.levels.INFO, { title = "Noctalia Bridge" })
    end)
  end)
end

return M
